# python中的array

In [3]:
from array import array
# 类型id+初始化
arr = array('i', [i for i in range(1, 8)])
with open("useful_folder/arr.bin", 'wb') as f:
	arr.tofile(f)
arr2 = array('i')
print(arr2)
with open("useful_folder/arr,bin", 'rb') as f:
	arr2.fromfile(f, 4)
print(arr2)

array('i')
array('i', [1, 2, 3, 4])


# Ndarray
![](Images/2022-03-24-01-12-10.png)

In [35]:
import numpy as np
# np.array
arr1 = np.array([1, 2, 3])
arr2 = np.array([1., 2, 3])
arr3 = np.array([1, 2, 3],dtype=float)
arr4 = np.array([1., 2, 3],dtype=int)
arr5 = np.array([i for i in range(1, 8)])
arr6 = np.array(set([1, 1, 3, 2]))
print(type(arr1))
print(type(arr1[0]))
print(type(arr2[0]))
print(arr1)
print(arr2) # 有小数全部变成小数
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(type(arr5))
print(type(arr6))

<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>
[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1 2 3]
[1 2 3 4 5 6 7]
{1, 2, 3}
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
# np.array的附加参数
a1 = np.array([1, 2, 3],dtype=float)
a2 = np.array([1., 2, 3],dtype=int)
a3 = np.array([1, 2, 3], order='C')
a4 = np.array([1, 2, 3], order='F')  # 保存元素的方式，不会显示出差别
a5 = np.array([1, 2, 3], ndmin=5)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)


[1 2 3]
[1 2 3]
[[[[[1 2 3]]]]]
[1 2 3 4 5 6 7]
{1, 2, 3}
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [36]:
# 定义array
a1 = np.ones((3, 4), dtype=complex)
a2 = np.ones_like((3, 4), dtype=float)
a3 = np.zeros((3, 4), dtype=complex)
a4 = np.zeros_like((3, 4), dtype=float)
a5 = np.full((2, 3), 7)
a6 = np.eye(3)
a7 = np.random.random((2, 3))
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[1. 1.]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[0. 0.]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.87486111 0.71044505 0.73286844]
 [0.6893115  0.45261792 0.39504636]]


In [40]:
# 数组属性
a1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a1.shape)
print(a1.ndim)
print(a1.size)  # shape乘积
print(a1.dtype)
print(a1.itemsize)  # 元素字节大小
print(a1.flags)  # 内存信息
print(a1.real)
print(a1.imag)
print(a1.data)  # 缓冲区
print(a1.strides) # 8字节走到下一个元素，24字节走到下一行元素

(2, 3)
2
6
int64
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]
(24, 8)


In [42]:
# reshape
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = a1.reshape((6))
a3 = a1.reshape((1, 2, 3))
a4 = a1.reshape((3, 2, -1))
print(a1)
print(a2)
print(a3)
print(a4)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 2 3]
  [4 5 6]]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [58]:
# 矩阵相加
import torch
import time
x = np.array([[i for i in range(1, 10000000)], [i for i in range(1, 10000000)]])
y = np.array([[i for i in range(1, 10000000)], [i for i in range(1, 10000000)]])
x_t = torch.tensor(x)
y_t = torch.tensor(y)
time1 = time.time()
x+y
time2 = time.time()
x_t+y_t
time3 = time.time()
np.add(x, y)
time4 = time.time()
x-y
time5 = time.time()
np.subtract(x, y)
time6 = time.time()
x*y
time7 = time.time()
x_t*y_t
time8 = time.time()
x/y
time9 = time.time()
np.divide(x, y)
time10 = time.time()
x_t/y_t
time11 = time.time()
np.sqrt(x)
print(time2-time1)
print(time3-time2)
print(time4-time3)
print(time5-time4)
print(time6-time5)
print(time7-time6)
print(time8-time7)
print(time9-time8)
print(time10-time9)
print(time11-time10)
# 发现时间相近！！！

0.032497406005859375
0.03466320037841797
0.03673887252807617
0.03975248336791992
0.0550074577331543
0.053078413009643555
0.044530630111694336
0.053530216217041016
0.054949045181274414
0.0560455322265625


In [70]:
# concatenate
x = np.array([[1, 3, 2], [6, 5, 4]])
y = np.array([[1, 1, 1], [1, 1, 1]])
z = np.concatenate((x, y), axis=0) # axis默认是0
w = np.concatenate((x, y), axis=1)
print(z)
print(w)
z.sort(axis=1)
print(z)
z.sort()
print(z)
print(np.argmax(z))


[[1 3 2]
 [6 5 4]
 [1 1 1]
 [1 1 1]]
[[1 3 2 1 1 1]
 [6 5 4 1 1 1]]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [1 1 1]
 [1 1 1]]
5


In [ ]:
# 广播机制
