In [2]:
import torch

In [3]:
# repeat
a = torch.tensor([[1, 2, 3], [3, 4, 5]])  # 2*3
b = a.repeat((1, 2))  # 2*6
c = a.repeat((2, 1))  # 4*3
d = a.repeat((1, 2, 3))  # 1*4*9
e = a.repeat((1, 1, 1))  # 1*2*3
print(a)
print(b)
print(c)
print(d.shape)
print(e.shape)

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1, 2, 3, 1, 2, 3],
        [3, 4, 5, 3, 4, 5]])
tensor([[1, 2, 3],
        [3, 4, 5],
        [1, 2, 3],
        [3, 4, 5]])
torch.Size([1, 4, 9])
torch.Size([1, 2, 3])


In [5]:
# permute 置换
x = torch.randn(2, 3, 5)
print(x.shape)
print(x)
x = x.permute(2, 0, 1)
print(x.shape)
print(x)

torch.Size([2, 3, 5])
tensor([[[ 0.0267,  1.2154, -0.4508,  0.9646,  1.2483],
         [-1.4421, -0.4723,  0.5368, -1.0809, -1.0782],
         [-0.4878,  0.1464,  0.3326,  0.5759,  0.7215]],

        [[-0.5848, -0.7556, -0.5885, -1.0141,  0.2248],
         [ 0.6022, -1.2206,  0.8756,  0.9993, -1.2468],
         [ 0.3774,  0.2345,  0.8087,  0.4206,  0.1563]]])
torch.Size([5, 2, 3])
tensor([[[ 0.0267, -1.4421, -0.4878],
         [-0.5848,  0.6022,  0.3774]],

        [[ 1.2154, -0.4723,  0.1464],
         [-0.7556, -1.2206,  0.2345]],

        [[-0.4508,  0.5368,  0.3326],
         [-0.5885,  0.8756,  0.8087]],

        [[ 0.9646, -1.0809,  0.5759],
         [-1.0141,  0.9993,  0.4206]],

        [[ 1.2483, -1.0782,  0.7215],
         [ 0.2248, -1.2468,  0.1563]]])
