In [1]:
import torch

In [2]:
# repeat
a = torch.tensor([[1, 2, 3], [3, 4, 5]])  # 2*3
b = a.repeat((1, 2))  # 2*6
c = a.repeat((2, 1))  # 4*3
d = a.repeat((1, 2, 3))  # 1*4*9
e = a.repeat((1, 1, 1))  # 1*2*3
print(a)
print(b)
print(c)
print(d.shape)
print(e.shape)

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1, 2, 3, 1, 2, 3],
        [3, 4, 5, 3, 4, 5]])
tensor([[1, 2, 3],
        [3, 4, 5],
        [1, 2, 3],
        [3, 4, 5]])
torch.Size([1, 4, 9])
torch.Size([1, 2, 3])


In [3]:
# permute 置换
x = torch.randn(2, 3, 5)
print(x.shape)
print(x)
x = x.permute(2, 0, 1)
print(x.shape)
print(x)

torch.Size([2, 3, 5])
tensor([[[ 0.9614, -0.1410,  0.3901,  2.7002,  0.1288],
         [-0.3735,  0.3699, -0.3304, -0.2866, -0.0275],
         [-0.4707,  0.2714, -1.1361,  1.3180, -2.2495]],

        [[-0.5228, -0.1276, -1.4814,  0.0572, -1.1219],
         [-1.0866,  0.4324,  1.0709,  1.6383, -0.1924],
         [ 0.7558,  1.5531, -1.2026,  2.2658,  0.2234]]])
torch.Size([5, 2, 3])
tensor([[[ 0.9614, -0.3735, -0.4707],
         [-0.5228, -1.0866,  0.7558]],

        [[-0.1410,  0.3699,  0.2714],
         [-0.1276,  0.4324,  1.5531]],

        [[ 0.3901, -0.3304, -1.1361],
         [-1.4814,  1.0709, -1.2026]],

        [[ 2.7002, -0.2866,  1.3180],
         [ 0.0572,  1.6383,  2.2658]],

        [[ 0.1288, -0.0275, -2.2495],
         [-1.1219, -0.1924,  0.2234]]])


In [6]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])  # 2*3
print(a.mean(dim=0))  # 3
print(a.mean(dim=1))  # 2

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


In [10]:
print(torch.cat((a, a), dim=0))  # 3*3->4*3
b = torch.unsqueeze(a, 2)
print(a.shape)
print(b.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.Size([2, 3, 1])
